include(CheckSymbolExists)
include(CheckIncludeFiles)

function(AC_HEADER_STDC)
  set(ac_cv_header_stdc_msg "Check for ANSI C header files")
  message(STATUS ${ac_cv_header_stdc_msg})
  check_include_files("stdlib.h;stdarg.h;string.h;float.h" ac_cv_header_stdc)
  if(ac_cv_header_stdc)
    check_symbol_exists(memchr "string.h" ac_cv_header_stdc)
  endif(ac_cv_header_stdc)
  if(ac_cv_header_stdc)
    check_symbol_exists(free "stdlib.h" ac_cv_header_stdc)
  endif(ac_cv_header_stdc)
  if(ac_cv_header_stdc)
    set(STDC_HEADERS 1 PARENT_SCOPE)
  endif(ac_cv_header_stdc)
  message(STATUS "${ac_cv_header_stdc_msg} -- ${ac_cv_header_stdc}")
endfunction(AC_HEADER_STDC)
