include(CheckIncludeFile)
include(CheckSymbolExists)

function(AC_HEADER_DIRENT)
  foreach(ac_hdr dirent.h sys/ndir.h sys/dir.h ndir.h)
    string(MAKE_C_IDENTIFIER ${ac_hdr} ac_hdr_variable)
    string(TOUPPER ${ac_hdr_variable} ac_hdr_variable)
    set(ac_hdr_variable HAVE_${ac_hdr_variable})
    set(ac_hdr_include sys/types.h ${ac_hdr})
    check_symbol_exists(DIR ${ac_hdr_include} ${ac_hdr_variable})
    set(${ac_hdr_variable} ${${${ac_hdr_variable}}} PARENT_SCOPE)
    if(${ac_hdr_variable})
      break()
    endif(${ac_hdr_variable})
  endforeach(ac_hdr)
endfunction(AC_HEADER_DIRENT)
