function(download_file URL OUTPUT_FILE RESULT_VAR)
  set(_download_message_prefix "downloading ${URL}")
  message(STATUS "${_download_message_prefix} ...")
  file(DOWNLOAD "${URL}" "${OUTPUT_FILE}" STATUS _status_var ${ARGN})
  list(GET _status_var 0 _status_code)
  list(REMOVE_AT _status_var 0)
  string(REGEX REPLACE "^\"" "" _status_text ${_status_var})
  string(REGEX REPLACE "\"$" "" _status_text ${_status_text})
  message(STATUS "\t" ${_status_text})
  if(${_status_code})
    message(STATUS "${_download_message_prefix} -- failed with code: ${_status_code}")
  else()
    message(STATUS "${_download_message_prefix} -- completed")
  endif()
  set(${RESULT_VAR} ${_status_code} PARENT_SCOPE)
endfunction(download_file)
