function(string_list_join LISTNAME RESULT_VAR SEPERATOR)
  list(LENGTH ${LISTNAME} _list_length)
  math(EXPR _list_length ${_list_length}-1)
  unset(_list_joined)
  foreach(_list_item_idx RANGE ${_list_length})
    list(GET ${LISTNAME} ${_list_item_idx} _list_item_value)
    if(_list_item_idx LESS _list_length)
      string(APPEND _list_joined "${_list_item_value}" "${SEPERATOR}")
    endif(_list_item_idx LESS _list_length)
  endforeach(_list_item_idx)
  set(${RESULT_VAR} "${_list_joined}" PARENT_SCOPE)
endfunction(string_list_join)
